### ISSUE TITLE
Warning when building go-redis storage

### ISSUE THREAD

**Issue by danielloader** [darkweak/storages#16]
```
go: warning: github.com/redis/go-redis/v9@v9.5.4: retracted by module author: This version was accidentally released. Please use version 9.6.0 instead.
```

Nothing too worrisome I imagine just worth bumping the go module soon.

**Comment by darkweak** [comment]
Hey @danielloader this issue will be patched in the #17. Thank you for your patience! 🙏

**Comment by darkweak** [comment]
Hey @danielloader the commit `29b5e6ae4cd7977b4eaf3b04c8a0dc12cf774293` in the PR #17 contains the dep bump. I'll close it once I merged the PR.

**Comment by danielloader** [comment]
Thanks again.
