### ISSUE TITLE
redis vs go-redis?

### ISSUE THREAD

**Issue by teodorescuserban** [darkweak/storages#18]
I may miss something but I am unable to see differences between redis and go-redis that are relevant to the caddy's cache handler.

Opinions, @darkweak ?

Thank you!

**Comment by darkweak** [comment]
Hello @teodorescuserban there was a memory consumption issue using redis (that uses `rueidis` under the hood) so I preferred to let the choice to the users about the redis client to use. Go-redis is more memory efficient than redis but redis is more performant so that depend on your need.
